### ISSUE TITLE
Bermasalah dengan perbandingan object

### ISSUE THREAD

**Issue by 4izenvalt** [4izenvalt/ProjectGrafis#4]
kami dari kelompok 9 [@Martino132 @nikoedyr ]dengan project UAS membuat object Helikopter ,
kami memiliki permasalahan karena mengerjakan potongan- potongan object helikopter secara individu sehingga terdapat perbedaan komposisi besar bendanya (badan & baling" nya)
![hell](https://user-images.githubusercontent.com/21327648/42436712-20851796-8385-11e8-9dbb-4a3862d88453.PNG)
jadi yang dipertanyakan apakah ada cara untuk memperbesar object tanpa mengubah koordinat awal object tersebut?

 @goFrendiAsgard

**Comment by goFrendiAsgard** [comment]
Tidak ada. Koordinat baling-balingnya harus diubah
